// Copyright 2017 - 2018 Code 4 Game, Org. All Rights Reserved.
// Don't edit this, it will be generated by builder.

#pragma once

#define GLTFFORUE4_MAJOR_VERSION 1
#define GLTFFORUE4_MINOR_VERSION 3
#define GLTFFORUE4_PATCH_VERSION 0
#define GLTFFORUE4_BUILD_NUMBER 52426917
